### ISSUE TITLE
Module crashes when trying to import image fields

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/feeds_para_mapper#1]
When trying to import content with images to an image field inside a paragraph, the Feeds importer crashes the whole session - every call to backend or frontend showing the error message
> call to unknown function module_implements()

Afterwards you have to clear all cookies to access the system again. But the Feeds import didn't work at all.

Error log shows multiple variants of the following error - with different key IDs:
> EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '37' for key 'PRIMARY' in ParagraphsItemController->save() (line 55 of [...]/modules/paragraphs/ParagraphsItemController.inc).

Importing the same image content to a field outside the paragraph works as intended.

This is probably related to the following issue:
https://github.com/backdrop-contrib/paragraphs/issues/31

**Comment by ghost** [comment]
Thanks for filing this issue @sternhagel. Unfortunately I'm no longer using this module so have marked this project as 'looking for maintainer(s)'. Let me know if you're interested.

**Comment by sternhagel** [comment]
@BWPanda Yes, I'd love to see this module working in Backdrop, so if there's nobody else interested in being maintainer, I'd be happy to step in.

**Comment by sternhagel** [comment]
This seems to have been an issue in the "Paragraphs" module fixed in this thread: https://github.com/backdrop-contrib/paragraphs/issues/38

So I think this issue should be closed.
